# Generated by Django 5.1.15 on 2026-09-07 13:10

import apps.properties.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_no', models.CharField(help_text='e.g. B-01', max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='buildings/')),
            ],
            options={
                'ordering': ['building_no'],
            },
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20, verbose_name='Alternate phone')),
                ('id_type', models.CharField(choices=[('nid', 'National ID (NID)'), ('passport', 'Passport'), ('driving', 'Driving Licence'), ('other', 'Other ID')], default='nid', max_length=12)),
                ('nid_number', models.CharField(blank=True, max_length=40, verbose_name='ID number')),
                ('present_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('occupation', models.CharField(blank=True, help_text='e.g. Service, Business', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(help_text='0 = Ground floor')),
                ('name', models.CharField(blank=True, help_text='e.g. Ground Floor', max_length=60)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='properties.building')),
            ],
            options={
                'ordering': ['building', 'level_number'],
                'unique_together': {('building', 'level_number')},
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=20)),
                ('flat_type', models.CharField(choices=[('flat', 'Flat'), ('shop', 'Shop'), ('cottage', 'Cottage')], default='flat', max_length=10)),
                ('size_sqft', models.PositiveIntegerField(blank=True, null=True, verbose_name='Size (sqft)')),
                ('amenities', models.TextField(blank=True, help_text='Comma separated, e.g. Lift, Generator, Parking')),
                ('default_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='properties.building')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='properties.level')),
            ],
            options={
                'ordering': ['building__building_no', 'flat_no'],
                'unique_together': {('building', 'flat_no')},
            },
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agreement_reference', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='properties.flat')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='properties.occupant')),
            ],
            options={
                'verbose_name_plural': 'Occupancies',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('nid', 'NID / ID Card'), ('agreement', 'Rental Agreement'), ('legal', 'Legal Proof'), ('photo', 'Photograph'), ('other', 'Other')], max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to=apps.properties.models.document_upload_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.occupant')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
